// <auto-generated />
using Kozos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kozos.Migrations
{
    [DbContext(typeof(VikingContext))]
    partial class VikingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kozos.Szamok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Szam1")
                        .HasColumnType("int");

                    b.Property<int>("Szam2")
                        .HasColumnType("int");

                    b.Property<int>("Szam3")
                        .HasColumnType("int");

                    b.Property<int>("Szam4")
                        .HasColumnType("int");

                    b.Property<int>("Szam5")
                        .HasColumnType("int");

                    b.Property<int>("Szam6")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LottoSzamok");
                });
#pragma warning restore 612, 618
        }
    }
}
